// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: S2C/LoginResult.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.S2C {

  /// <summary>Holder for reflection information generated from S2C/LoginResult.proto</summary>
  public static partial class LoginResultReflection {

    #region Descriptor
    /// <summary>File descriptor for S2C/LoginResult.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginResultReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVTMkMvTG9naW5SZXN1bHQucHJvdG8SDFByb3RvYnVmLlMyQyI6CgtMb2dp",
            "blJlc3VsdBIUCgxsb2dpblN1Y2Nlc3MYASABKAgSFQoNU2Vzc2lvblRpY2tl",
            "dBgCIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.S2C.LoginResult), global::Protobuf.S2C.LoginResult.Parser, new[]{ "LoginSuccess", "SessionTicket" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LoginResult : pb::IMessage<LoginResult> {
    private static readonly pb::MessageParser<LoginResult> _parser = new pb::MessageParser<LoginResult>(() => new LoginResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.S2C.LoginResultReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginResult(LoginResult other) : this() {
      loginSuccess_ = other.loginSuccess_;
      sessionTicket_ = other.sessionTicket_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginResult Clone() {
      return new LoginResult(this);
    }

    /// <summary>Field number for the "loginSuccess" field.</summary>
    public const int LoginSuccessFieldNumber = 1;
    private bool loginSuccess_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool LoginSuccess {
      get { return loginSuccess_; }
      set {
        loginSuccess_ = value;
      }
    }

    /// <summary>Field number for the "SessionTicket" field.</summary>
    public const int SessionTicketFieldNumber = 2;
    private string sessionTicket_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SessionTicket {
      get { return sessionTicket_; }
      set {
        sessionTicket_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginSuccess != other.LoginSuccess) return false;
      if (SessionTicket != other.SessionTicket) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginSuccess != false) hash ^= LoginSuccess.GetHashCode();
      if (SessionTicket.Length != 0) hash ^= SessionTicket.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginSuccess != false) {
        output.WriteRawTag(8);
        output.WriteBool(LoginSuccess);
      }
      if (SessionTicket.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionTicket);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginSuccess != false) {
        size += 1 + 1;
      }
      if (SessionTicket.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionTicket);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginResult other) {
      if (other == null) {
        return;
      }
      if (other.LoginSuccess != false) {
        LoginSuccess = other.LoginSuccess;
      }
      if (other.SessionTicket.Length != 0) {
        SessionTicket = other.SessionTicket;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LoginSuccess = input.ReadBool();
            break;
          }
          case 18: {
            SessionTicket = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
